name: Packer Build CI

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    name: Packer Build CI

    runs-on: ubuntu-latest

    env:
      MYSQL_USER: ${{ secrets.MYSQL_USER }}
      MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
      MYSQL_HOST: ${{ secrets.MYSQL_HOST }}
      MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
      STARTUP_SCRIPT: |
        #!/bin/bash

        echo "Starting startup script..."

        sudo sh -c  'cat << EOF > /opt/app/.env
        MYSQL_HOST=10.109.0.2
        MYSQL_USER=webapp
        MYSQL_PASSWORD=3?TUr{YFqojzFfLf
        MYSQL_DATABASE=webapp
        EOF'

        echo "Startup script executed successfully!"

    strategy:
      matrix:
        node-version: [21.x]

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    # - name: Setup MySQL
    #   run: |
    #     sudo /etc/init.d/mysql start
    #     mysql -h ${{secrets.MYSQL_HOST}} --port 3306 -u${{secrets.MYSQL_USER}} -p${{secrets.MYSQL_PASSWORD}} -e "CREATE DATABASE ${{ secrets.MYSQL_DATABASE }};"

    # - name: Install Dependencies
    #   run: npm ci

    # - name: Run Integration Tests
    #   run: npm test

    # - name: Drop DB
    #   run: mysql -h ${{secrets.MYSQL_HOST}} --port 3306 -u${{secrets.MYSQL_USER}} -p${{secrets.MYSQL_PASSWORD}} -e "DROP DATABASE ${{ secrets.MYSQL_DATABASE }};"

    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v2'

    - name: 'Use gcloud CLI'
      run: 'gcloud info'

    - name: Build application artifact (.zip)
      run: npm run build

    # - name: Packer Init
    #   run: packer init packer/packer.pkr.hcl

    # - name: Packer Build
    #   run: packer build -force -var "credentials_file=$GOOGLE_APPLICATION_CREDENTIALS" -var "project_id=${{ secrets.GCP_PROJECT_ID }}" packer/packer.pkr.hcl

    - name: Create new Instance Template
      run:
        gcloud compute instance-templates create packer-instance-template --machine-type=e2-standard-2 --instance-template-region=us-east1 --create-disk="image=packer-img-with-cloud-db,auto-delete=yes,boot=yes,type=pd-ssd,size=40GB,kms-key=projects/cloud--dev/locations/us-east1/keyRings/my-key-ring5/cryptoKeys/vm-disk-key" --network-interface="network=network1,subnet=webapp" --service-account=vm-service-account@cloud--dev.iam.gserviceaccount.com --scopes=https://www.googleapis.com/auth/logging.write,https://www.googleapis.com/auth/monitoring.write,https://www.googleapis.com/auth/pubsub --metadata=startup-script=${{ env.STARTUP_SCRIPT }}