name: Packer Build CI

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    name: Packer Build CI

    runs-on: ubuntu-latest

    env:
      MYSQL_USER: ${{ secrets.MYSQL_USER }}
      MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
      MYSQL_HOST: ${{ secrets.MYSQL_HOST }}
      MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}

    strategy:
      matrix:
        node-version: [21.x]

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Setup MySQL
      run: |
        sudo /etc/init.d/mysql start
        mysql -h ${{secrets.MYSQL_HOST}} --port 3306 -u${{secrets.MYSQL_USER}} -p${{secrets.MYSQL_PASSWORD}} -e "CREATE DATABASE ${{ secrets.MYSQL_DATABASE }};"

    - name: Install Dependencies
      run: npm ci

    - name: Run Integration Tests
      run: npm test

    - name: Drop DB
      run: mysql -h ${{secrets.MYSQL_HOST}} --port 3306 -u${{secrets.MYSQL_USER}} -p${{secrets.MYSQL_PASSWORD}} -e "DROP DATABASE ${{ secrets.MYSQL_DATABASE }};"
    
    - name: Build application artifact (.zip)
      run: npm run build

    - name: Setup GCP creds
      env:
        GCP_SERVICE_ACC_KEY: ${{ secrets.GCP_SERVICE_ACC_KEY }}
      run: echo $GCP_SERVICE_ACC_KEY | base64 --decode > GCP_SERVICE_ACC_KEY.json

    - name: Packer Init
      run: packer init packer/packer.pkr.hcl

    - name: Packer Build
      run: packer build -force -var 'project_id=${{ secrets.GCP_PROJECT_ID }}' -var 'credentials_file=GCP_SERVICE_ACC_KEY.json' packer/packer.pkr.hcl